### ISSUE TITLE
How Many Records (candidate/job) can Access an API call Maximum?

### ISSUE THREAD

**Issue by sikderg** [kkiernan/bullhorn-php-client#3]
Dear Sir,
I have seen you have done quite research on Bullhorn API.
Can you Guide me?
How Many Records (candidate/job) can Access an SOAP-API call Maximum?

**Comment by kkiernan** [comment]
Hello @developergoutam,

Sorry I didn't see your question before. I haven't worked on this in quite some time, but when I originally made the wrapper, I believe the API was limited to 20 entities at a time. The findMultiple method takes this into consideration and "chunks" the results for you. Assuming you don't hit a max execution time limit, I think you should be ok.
